import { defineConfig } from "vite";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  // Order matters. wasm() sits at the start of the chain: converts .wasm import
  // into an instantiate call. Every subsequent plugin sees its output.
  plugins: [wasm()],

  build: {
    // Required for top-level await generated by wasm() to work.
    // Alternative: plugins: [wasm(), topLevelAwait()] — ~73 KB larger.
    target: "esnext",

    // Vite default is already 4096; explicitly declared here.
    // If this count exceeds 1,570,176, .wasm will be embedded as base64
    // into JS and all advantages will be lost.
    assetsInlineLimit: 4096,
  },

  // Keep dev server dependency optimizer away from Rapier.
  // Reason below: dev behaves differently from build.
  optimizeDeps: { exclude: ["@dimforge/rapier3d"] },
});
