import { createSim, type RapierApi } from "./sim";

/**
 * THIRD solution to TLA error: wrap await inside an async function.
 * Only valid for the -compat track — because you write the await yourself there.
 * In pure ESM that await resides inside a dependency generated by the plugin.
 *
 * This file is not the demo entry point; runs via `npm run bootstrap-async` and
 * outputs the exact same number as the tests: y = 0.49872392416000366.
 */
function startGame(R: RapierApi): void {
  const { world, bodies } = createSim(R, 8);
  for (let i = 0; i < 120; i++) world.step();
  console.log("y =", bodies[0].translation().y);
}

async function bootstrap() {
  const RAPIER = await import("@dimforge/rapier3d-compat");
  await RAPIER.init();
  startGame(RAPIER as unknown as RapierApi);
}
void bootstrap();
