import type { RapierApi } from "./sim";
import { createSim } from "./sim";

export interface SetupReport {
  version: string;
  /** timestep is stored as f32 in WASM; MUST NOT equal JS f64. */
  crossesWasmBoundary: boolean;
  /** Was a real .wasm request detected on the network? (pure ESM: yes, -compat: no) */
  separateWasmRequest: boolean;
  /** Does running the same setup twice produce bit-for-bit identical results? */
  deterministic: boolean;
  finalY: number;
}

export function auditSetup(R: RapierApi): SetupReport {
  // 1) Is engine truly running? version() round-trips to WASM.
  const version = R.version();

  // 2) f32 boundary: write 1/60, read back. If this were a pure JS stub,
  //    it would return the exact same f64 number. WASM rounds value to f32.
  const probe = new R.World({ x: 0, y: 0, z: 0 });
  probe.timestep = 1 / 60;
  const crossesWasmBoundary = probe.timestep !== 1 / 60;

  // 3) Programmatic check on network resources.
  //    Loose `.includes(".wasm")` here is INTENTIONAL: answer is boolean, and
  //    all three URLs generated by Vite (?import, ?import&url, raw) yield same answer.
  //    `hud.ts` measures BYTES and MUST distinguish them; filter there is exact.
  const separateWasmRequest =
    typeof performance !== "undefined" &&
    performance
      .getEntriesByType("resource")
      .some((e) => e.name.includes(".wasm"));

  // 4) Determinism: two identical worlds, identical step count, identical result.
  const a = createSim(R, 8);
  const b = createSim(R, 8);
  for (let i = 0; i < 120; i++) {
    a.world.step();
    b.world.step();
  }
  const ay = a.bodies[0].translation().y;
  const by = b.bodies[0].translation().y;

  return {
    version,
    crossesWasmBoundary,
    separateWasmRequest,
    deterministic: ay === by,
    finalY: ay,
  };
}
